In [1]:
import pandas as pd

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder
import pickle

In [3]:
## Load Data 
df = pd.read_csv("Churn_Modelling.csv")

In [4]:
df['Exited'].value_counts()

Exited
0    7963
1    2037
Name: count, dtype: int64

In [43]:
df.head(2)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0

In [44]:
# Preprocessing Data

X = df.iloc[:,3:-1]
y = df.iloc[:,-1]

In [45]:
X

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,619,France,Female,42,2,0.00,1,1,1,101348.88
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58
2,502,France,Female,42,8,159660.80,3,1,0,113931.57
3,699,France,Female,39,1,0.00,2,0,0,93826.63
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10
...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77
9997,709,France,Female,36,7,0.00,1,0,1,42085.58
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78

In [46]:
df['Gender'].value_counts()
df['Gender'].unique()

array(['Female', 'Male'], dtype=object)

In [47]:
encoder  = LabelEncoder()
X['Gender']=encoder.fit_transform(X['Gender'])

In [48]:
X

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,619,France,0,42,2,0.00,1,1,1,101348.88
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58
2,502,France,0,42,8,159660.80,3,1,0,113931.57
3,699,France,0,39,1,0.00,2,0,0,93826.63
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10
...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64
9996,516,France,1,35,10,57369.61,1,1,1,101699.77
9997,709,France,0,36,7,0.00,1,0,1,42085.58
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52
9999,792,France,0,28,4,130142.79,1,1,0,38190.78

In [49]:
df['Geography'].unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [50]:
## OHE on Geography

from sklearn.preprocessing import OneHotEncoder
ohe_encoder = OneHotEncoder(sparse_output=False)
geo_encoded = ohe_encoder.fit_transform(df[['Geography']])

In [51]:
geo_encoded

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]], shape=(10000, 3))

In [52]:
ohe_encoder.get_feature_names_out()

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [53]:
geo_encoded_df = pd.DataFrame(geo_encoded,columns = ohe_encoder.get_feature_names_out())

In [54]:
X = pd.concat([X,geo_encoded_df],axis = 1)

In [55]:
X

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,619,France,0,42,2,0.00,1,1,1,101348.88,1.0,0.0,0.0
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0.0,0.0,1.0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1.0,0.0,0.0
3,699,France,0,39,1,0.00,2,0,0,93826.63,1.0,0.0,0.0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,1.0,0.0,0.0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,1.0,0.0,0.0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1.0,0.0,0.0
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,0.0,1.0,0.0
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,1.0,0.0,0.0

In [56]:
X.drop(['Geography'],axis=1,inplace=True)

In [57]:
X

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,1.0,0.0,0.0

In [58]:
y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [ ]:
## Save encder and Scalers
with open('label_encoder_geography.pkl','wb') as file:
    pickle.dump(ohe_encoder,file)

with open('label_encoder_gender.pkl','wb') as file:
    pickle.dump(encoder,file)

In [60]:
X_train,X_test,Y_train,Y_test = train_test_split(X,y,test_size = 0.2,random_state = 42)

In [61]:
X_train

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
9254,686,1,32,6,0.00,2,1,1,179093.26,1.0,0.0,0.0
1561,632,1,42,4,119624.60,2,1,1,195978.86,0.0,1.0,0.0
1670,559,1,24,3,114739.92,1,1,0,85891.02,0.0,0.0,1.0
6087,561,0,27,9,135637.00,1,1,0,153080.40,1.0,0.0,0.0
6669,517,1,56,9,142147.32,1,0,0,39488.04,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
5734,768,1,54,8,69712.74,1,1,1,69381.05,1.0,0.0,0.0
5191,682,0,58,1,0.00,1,1,1,706.50,1.0,0.0,0.0
5390,735,0,38,1,0.00,3,0,0,92220.12,1.0,0.0,0.0
860,667,1,43,8,190227.46,1,1,0,97508.04,1.0,0.0,0.0
7270,697,1,51,1,147910.30,1,1,1,53581.14,0.0,1.0,0.0

In [62]:
# Scaling Features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [63]:
X_train.shape

(8000, 12)

In [64]:
with open('scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

In [65]:
X_test_tensor.shape

torch.Size([8000, 12])

In [66]:
import torch
import torch.nn as nn

In [67]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)

In [68]:
Y_train_tensor = torch.tensor(Y_train.values)

In [69]:
Y_test_tensor = torch.tensor(Y_test.values)

In [70]:
class AnnModel(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(num_features.shape[1],8),
            nn.ReLU(),
            nn.Linear(8,4),
            nn.ReLU(),
            nn.Linear(4,1),
            nn.Sigmoid()
        )
    def forward(self,features):
        output = self.network(features)
        return output

In [71]:
X_test_tensor.shape

torch.Size([2000, 12])

In [102]:
model = AnnModel(X_train_tensor)
Learning_rate = 0.1
epochs = 5000
Loss_function = nn.BCELoss()
optimizer = torch.optim.SGD(model.parameters(),Learning_rate)

In [ ]:
Y_train_tensor = Y_train_tensor.view(-1,1).to(torch.float32)
# y_pred = y_pred.view(-1,1).to(torch.float32)
from torch.utils.tensorboard import SummaryWriter
# writer = SummaryWriter('runs/ann_experiment_1')

for epoch in range(epochs):
    y_pred = model(X_train_tensor.to(torch.float32))
    loss = Loss_function(y_pred,Y_train_tensor.to(torch.float32))
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    print(f"Epoch: {epoch+1},Loss: {loss.item()}")
    # writer.add_scalar('Loss/train', loss.item(), epoch)
# writer.close()

Epoch: 1,Loss: 0.3290444612503052
Epoch: 2,Loss: 0.3290429413318634
Epoch: 3,Loss: 0.3290414810180664
Epoch: 4,Loss: 0.329039990901947
Epoch: 5,Loss: 0.32903850078582764
Epoch: 6,Loss: 0.32903704047203064
Epoch: 7,Loss: 0.3290356397628784
Epoch: 8,Loss: 0.32903414964675903
Epoch: 9,Loss: 0.3290327191352844
Epoch: 10,Loss: 0.3290312886238098
Epoch: 11,Loss: 0.32902979850769043
Epoch: 12,Loss: 0.3290281295776367
Epoch: 13,Loss: 0.3290264904499054
Epoch: 14,Loss: 0.3290247917175293
Epoch: 15,Loss: 0.3290230333805084
Epoch: 16,Loss: 0.32902130484580994
Epoch: 17,Loss: 0.32901957631111145
Epoch: 18,Loss: 0.3290178179740906
Epoch: 19,Loss: 0.3290161192417145
Epoch: 20,Loss: 0.32901421189308167
Epoch: 21,Loss: 0.329012393951416
Epoch: 22,Loss: 0.3290105164051056
Epoch: 23,Loss: 0.3290087580680847
Epoch: 24,Loss: 0.32900699973106384
Epoch: 25,Loss: 0.32900524139404297
Epoch: 26,Loss: 0.3290034830570221
Epoch: 27,Loss: 0.32900169491767883
Epoch: 28,Loss: 0.32899993658065796
Epoch: 29,Loss: 0.3289981782436371
Epoch: 30,Loss: 0.32899630069732666
Epoch: 31,Loss: 0.3289945423603058
Epoch: 32,Loss: 0.3289927542209625
Epoch: 33,Loss: 0.32899096608161926
Epoch: 34,Loss: 0.32898929715156555
Epoch: 35,Loss: 0.3289875388145447
Epoch: 36,Loss: 0.3289857804775238
Epoch: 37,Loss: 0.3289841115474701
Epoch: 38,Loss: 0.3289824426174164
Epoch: 39,Loss: 0.3289807438850403
Epoch: 40,Loss: 0.3289788067340851
Epoch: 41,Loss: 0.32897698879241943
Epoch: 42,Loss: 0.328975111246109
Epoch: 43,Loss: 0.3289732336997986
Epoch: 44,Loss: 0.3289714753627777
Epoch: 45,Loss: 0.32896965742111206
Epoch: 46,Loss: 0.3289678692817688
Epoch: 47,Loss: 0.3289661705493927
Epoch: 48,Loss: 0.3289644420146942
Epoch: 49,Loss: 0.3289627432823181
Epoch: 50,Loss: 0.32896101474761963
Epoch: 51,Loss: 0.32895931601524353
Epoch: 52,Loss: 0.32895758748054504
Epoch: 53,Loss: 0.32895585894584656
Epoch: 54,Loss: 0.32895413041114807
Epoch: 55,Loss: 0.3289524018764496
Epoch: 56,Loss: 0.3289506137371063
Epoch: 57,Loss: 0.32894888520240784
Epoch: 58,Loss: 0.32894715666770935
Epoch: 59,Loss: 0.32894542813301086
Epoch: 60,Loss: 0.3289436995983124
Epoch: 61,Loss: 0.3289419412612915
Epoch: 62,Loss: 0.3289402723312378
Epoch: 63,Loss: 0.3289385735988617
Epoch: 64,Loss: 0.3289368748664856
Epoch: 65,Loss: 0.3289351761341095
Epoch: 66,Loss: 0.3289335370063782
Epoch: 67,Loss: 0.32893186807632446
Epoch: 68,Loss: 0.32893016934394836
Epoch: 69,Loss: 0.32892856001853943
Epoch: 70,Loss: 0.3289268910884857
Epoch: 71,Loss: 0.328925222158432
Epoch: 72,Loss: 0.3289234936237335
Epoch: 73,Loss: 0.3289217948913574
Epoch: 74,Loss: 0.32892000675201416
Epoch: 75,Loss: 0.3289182782173157
Epoch: 76,Loss: 0.3289164900779724
Epoch: 77,Loss: 0.32891473174095154
Epoch: 78,Loss: 0.32891297340393066
Epoch: 79,Loss: 0.32891106605529785
Epoch: 80,Loss: 0.3289092183113098
Epoch: 81,Loss: 0.32890722155570984
Epoch: 82,Loss: 0.32890528440475464
Epoch: 83,Loss: 0.3289032578468323
Epoch: 84,Loss: 0.3289012610912323
Epoch: 85,Loss: 0.3288992643356323
Epoch: 86,Loss: 0.32889723777770996
Epoch: 87,Loss: 0.3288952708244324
Epoch: 88,Loss: 0.32889324426651
Epoch: 89,Loss: 0.32889124751091003
Epoch: 90,Loss: 0.32888925075531006
Epoch: 91,Loss: 0.3288872539997101
Epoch: 92,Loss: 0.32888537645339966
Epoch: 93,Loss: 0.32888340950012207
Epoch: 94,Loss: 0.3288814425468445
Epoch: 95,Loss: 0.32887953519821167
Epoch: 96,Loss: 0.32887765765190125
Epoch: 97,Loss: 0.32887572050094604
Epoch: 98,Loss: 0.3288738429546356
Epoch: 99,Loss: 0.3288719654083252
Epoch: 100,Loss: 0.32887002825737
Epoch: 101,Loss: 0.32886800169944763
Epoch: 102,Loss: 0.32886600494384766
Epoch: 103,Loss: 0.3288640081882477
Epoch: 104,Loss: 0.3288620114326477
Epoch: 105,Loss: 0.32885992527008057
Epoch: 106,Loss: 0.3288578987121582
Epoch: 107,Loss: 0.32885587215423584
Epoch: 108,Loss: 0.32885387539863586
Epoch: 109,Loss: 0.32885199785232544
Epoch: 110,Loss: 0.3288500905036926
Epoch: 111,Loss: 0.3288482427597046
Epoch: 112,Loss: 0.32884636521339417
Epoch: 113,Loss: 0.3288445472717285
Epoch: 114,Loss: 0.32884272933006287
Epoch: 115,Loss: 0.32884085178375244
Epoch: 116,Loss: 0.32883891463279724
Epoch: 117,Loss: 0.32883700728416443
Epoch: 118,Loss: 0.32883521914482117
Epoch: 119,Loss: 0.32883337140083313
Epoch: 120,Loss: 0.3288315534591675
Epoch: 121,Loss: 0.3288296163082123
Epoch: 122,Loss: 0.32882770895957947
Epoch: 123,Loss: 0.32882586121559143
Epoch: 124,Loss: 0.3288240134716034
Epoch: 125,Loss: 0.32882222533226013
Epoch: 126,Loss: 0.3288203775882721
Epoch: 127,Loss: 0.3288184702396393
Epoch: 128,Loss: 0.3288167119026184
Epoch: 129,Loss: 0.32881486415863037
Epoch: 130,Loss: 0.32881301641464233
Epoch: 131,Loss: 0.3288111984729767
Epoch: 132,Loss: 0.32880935072898865
Epoch: 133,Loss: 0.3288075625896454
Epoch: 134,Loss: 0.32880574464797974
Epoch: 135,Loss: 0.3288039267063141
Epoch: 136,Loss: 0.3288021385669708
Epoch: 137,Loss: 0.3288002610206604
Epoch: 138,Loss: 0.32879844307899475
Epoch: 139,Loss: 0.3287965655326843
Epoch: 140,Loss: 0.3287946581840515
Epoch: 141,Loss: 0.32879289984703064
Epoch: 142,Loss: 0.328791081905365
Epoch: 143,Loss: 0.32878926396369934
Epoch: 144,Loss: 0.3287874460220337
Epoch: 145,Loss: 0.32878562808036804
Epoch: 146,Loss: 0.3287837505340576
Epoch: 147,Loss: 0.32878199219703674
Epoch: 148,Loss: 0.3287802040576935
Epoch: 149,Loss: 0.3287784159183502
Epoch: 150,Loss: 0.32877659797668457
Epoch: 151,Loss: 0.32877489924430847
Epoch: 152,Loss: 0.32877326011657715
Epoch: 153,Loss: 0.3287717401981354
Epoch: 154,Loss: 0.32877016067504883
Epoch: 155,Loss: 0.3287685811519623
Epoch: 156,Loss: 0.3287670314311981
Epoch: 157,Loss: 0.32876551151275635
Epoch: 158,Loss: 0.3287639021873474
Epoch: 159,Loss: 0.32876238226890564
Epoch: 160,Loss: 0.3287608027458191
Epoch: 161,Loss: 0.32875922322273254
Epoch: 162,Loss: 0.3287575840950012
Epoch: 163,Loss: 0.3287559151649475
Epoch: 164,Loss: 0.3287542760372162
Epoch: 165,Loss: 0.32875263690948486
Epoch: 166,Loss: 0.32875096797943115
Epoch: 167,Loss: 0.3287493884563446
Epoch: 168,Loss: 0.3287476599216461
Epoch: 169,Loss: 0.3287459909915924
Epoch: 170,Loss: 0.3287443518638611
Epoch: 171,Loss: 0.3287426829338074
Epoch: 172,Loss: 0.32874101400375366
Epoch: 173,Loss: 0.32873934507369995
Epoch: 174,Loss: 0.32873764634132385
Epoch: 175,Loss: 0.32873594760894775
Epoch: 176,Loss: 0.32873421907424927
Epoch: 177,Loss: 0.3287324011325836
Epoch: 178,Loss: 0.32873058319091797
Epoch: 179,Loss: 0.3287288248538971
Epoch: 180,Loss: 0.3287270665168762
Epoch: 181,Loss: 0.32872530817985535
Epoch: 182,Loss: 0.3287235498428345
Epoch: 183,Loss: 0.3287217915058136
Epoch: 184,Loss: 0.32872000336647034
Epoch: 185,Loss: 0.32871824502944946
Epoch: 186,Loss: 0.3287164270877838
Epoch: 187,Loss: 0.3287147283554077
Epoch: 188,Loss: 0.32871294021606445
Epoch: 189,Loss: 0.3287111818790436
Epoch: 190,Loss: 0.3287094533443451
Epoch: 191,Loss: 0.3287077248096466
Epoch: 192,Loss: 0.3287060260772705
Epoch: 193,Loss: 0.3287043273448944
Epoch: 194,Loss: 0.3287025988101959
Epoch: 195,Loss: 0.3287009298801422
Epoch: 196,Loss: 0.3286992907524109
Epoch: 197,Loss: 0.32869765162467957
Epoch: 198,Loss: 0.32869604229927063
Epoch: 199,Loss: 0.32869449257850647
Epoch: 200,Loss: 0.3286926746368408
Epoch: 201,Loss: 0.32869085669517517
Epoch: 202,Loss: 0.3286890983581543
Epoch: 203,Loss: 0.32868725061416626
Epoch: 204,Loss: 0.3286855220794678
Epoch: 205,Loss: 0.3286837339401245
Epoch: 206,Loss: 0.3286818861961365
Epoch: 207,Loss: 0.3286799490451813
Epoch: 208,Loss: 0.3286781311035156
Epoch: 209,Loss: 0.32867634296417236
Epoch: 210,Loss: 0.3286745250225067
Epoch: 211,Loss: 0.32867270708084106
Epoch: 212,Loss: 0.3286709487438202
Epoch: 213,Loss: 0.3286692500114441
Epoch: 214,Loss: 0.328667551279068
Epoch: 215,Loss: 0.3286657929420471
Epoch: 216,Loss: 0.328664094209671
Epoch: 217,Loss: 0.3286624252796173
Epoch: 218,Loss: 0.32866066694259644
Epoch: 219,Loss: 0.32865896821022034
Epoch: 220,Loss: 0.32865723967552185
Epoch: 221,Loss: 0.3286554515361786
Epoch: 222,Loss: 0.3286537230014801
Epoch: 223,Loss: 0.32865196466445923
Epoch: 224,Loss: 0.32865026593208313
Epoch: 225,Loss: 0.32864853739738464
Epoch: 226,Loss: 0.32864677906036377
Epoch: 227,Loss: 0.32864511013031006
Epoch: 228,Loss: 0.32864344120025635
Epoch: 229,Loss: 0.3286416232585907
Epoch: 230,Loss: 0.3286398649215698
Epoch: 231,Loss: 0.3286380171775818
Epoch: 232,Loss: 0.3286363482475281
Epoch: 233,Loss: 0.3286346197128296
Epoch: 234,Loss: 0.3286328613758087
Epoch: 235,Loss: 0.3286311626434326
Epoch: 236,Loss: 0.32862937450408936
Epoch: 237,Loss: 0.3286276161670685
Epoch: 238,Loss: 0.3286258578300476
Epoch: 239,Loss: 0.32862406969070435
Epoch: 240,Loss: 0.32862231135368347
Epoch: 241,Loss: 0.3286205232143402
Epoch: 242,Loss: 0.32861870527267456
Epoch: 243,Loss: 0.32861682772636414
Epoch: 244,Loss: 0.3286149501800537
Epoch: 245,Loss: 0.3286130130290985
Epoch: 246,Loss: 0.3286111056804657
Epoch: 247,Loss: 0.32860931754112244
Epoch: 248,Loss: 0.3286074995994568
Epoch: 249,Loss: 0.3286057412624359
Epoch: 250,Loss: 0.3286040127277374
Epoch: 251,Loss: 0.32860225439071655
Epoch: 252,Loss: 0.32860058546066284
Epoch: 253,Loss: 0.32859885692596436
Epoch: 254,Loss: 0.32859718799591064
Epoch: 255,Loss: 0.3285956084728241
Epoch: 256,Loss: 0.32859402894973755
Epoch: 257,Loss: 0.328592449426651
Epoch: 258,Loss: 0.32859089970588684
Epoch: 259,Loss: 0.32858940958976746
Epoch: 260,Loss: 0.3285878002643585
Epoch: 261,Loss: 0.32858625054359436
Epoch: 262,Loss: 0.3285847306251526
Epoch: 263,Loss: 0.32858312129974365
Epoch: 264,Loss: 0.3285816013813019
Epoch: 265,Loss: 0.3285800814628601
Epoch: 266,Loss: 0.32857856154441833
Epoch: 267,Loss: 0.3285770118236542
Epoch: 268,Loss: 0.3285755217075348
Epoch: 269,Loss: 0.32857397198677063
Epoch: 270,Loss: 0.32857251167297363
Epoch: 271,Loss: 0.32857105135917664
Epoch: 272,Loss: 0.32856953144073486
Epoch: 273,Loss: 0.3285680115222931
Epoch: 274,Loss: 0.3285665214061737
Epoch: 275,Loss: 0.32856515049934387
Epoch: 276,Loss: 0.3285636901855469
Epoch: 277,Loss: 0.32856234908103943
Epoch: 278,Loss: 0.328561007976532
Epoch: 279,Loss: 0.328559547662735
Epoch: 280,Loss: 0.3285581171512604
Epoch: 281,Loss: 0.32855677604675293
Epoch: 282,Loss: 0.3285553455352783
Epoch: 283,Loss: 0.3285538852214813
Epoch: 284,Loss: 0.3285524547100067
Epoch: 285,Loss: 0.3285509943962097
Epoch: 286,Loss: 0.32854947447776794
Epoch: 287,Loss: 0.32854798436164856
Epoch: 288,Loss: 0.32854655385017395
Epoch: 289,Loss: 0.32854506373405457
Epoch: 290,Loss: 0.32854360342025757
Epoch: 291,Loss: 0.32854217290878296
Epoch: 292,Loss: 0.32854077219963074
Epoch: 293,Loss: 0.32853934168815613
Epoch: 294,Loss: 0.32853788137435913
Epoch: 295,Loss: 0.3285364508628845
Epoch: 296,Loss: 0.32853490114212036
Epoch: 297,Loss: 0.32853350043296814
Epoch: 298,Loss: 0.32853204011917114
Epoch: 299,Loss: 0.3285306692123413
Epoch: 300,Loss: 0.3285292387008667
Epoch: 301,Loss: 0.32852786779403687
Epoch: 302,Loss: 0.32852643728256226
Epoch: 303,Loss: 0.3285248875617981
Epoch: 304,Loss: 0.32852330803871155
Epoch: 305,Loss: 0.32852184772491455
Epoch: 306,Loss: 0.3285202085971832
Epoch: 307,Loss: 0.32851871848106384
Epoch: 308,Loss: 0.3285171389579773
Epoch: 309,Loss: 0.3285156190395355
Epoch: 310,Loss: 0.3285141587257385
Epoch: 311,Loss: 0.3285127282142639
Epoch: 312,Loss: 0.3285112977027893
Epoch: 313,Loss: 0.3285098373889923
Epoch: 314,Loss: 0.3285084664821625
Epoch: 315,Loss: 0.3285070061683655
Epoch: 316,Loss: 0.32850557565689087
Epoch: 317,Loss: 0.32850417494773865
Epoch: 318,Loss: 0.3285028040409088
Epoch: 319,Loss: 0.3285013735294342
Epoch: 320,Loss: 0.3284998834133148
Epoch: 321,Loss: 0.328498512506485
Epoch: 322,Loss: 0.328497052192688
Epoch: 323,Loss: 0.3284955322742462
Epoch: 324,Loss: 0.328494131565094
Epoch: 325,Loss: 0.3284926116466522
Epoch: 326,Loss: 0.3284912109375
Epoch: 327,Loss: 0.3284897208213806
Epoch: 328,Loss: 0.32848837971687317
Epoch: 329,Loss: 0.3284868896007538
Epoch: 330,Loss: 0.3284854590892792
Epoch: 331,Loss: 0.32848402857780457
Epoch: 332,Loss: 0.32848256826400757
Epoch: 333,Loss: 0.32848116755485535
Epoch: 334,Loss: 0.32847970724105835
Epoch: 335,Loss: 0.32847830653190613
Epoch: 336,Loss: 0.32847678661346436
Epoch: 337,Loss: 0.32847535610198975
Epoch: 338,Loss: 0.328473836183548
Epoch: 339,Loss: 0.3284722864627838
Epoch: 340,Loss: 0.3284708261489868
Epoch: 341,Loss: 0.32846933603286743
Epoch: 342,Loss: 0.32846784591674805
Epoch: 343,Loss: 0.3284662961959839
Epoch: 344,Loss: 0.3284648358821869
Epoch: 345,Loss: 0.32846328616142273
Epoch: 346,Loss: 0.3284618854522705
Epoch: 347,Loss: 0.32846030592918396
Epoch: 348,Loss: 0.3284587562084198
Epoch: 349,Loss: 0.3284572660923004
Epoch: 350,Loss: 0.3284558057785034
Epoch: 351,Loss: 0.3284543454647064
Epoch: 352,Loss: 0.3284527659416199
Epoch: 353,Loss: 0.3284512758255005
Epoch: 354,Loss: 0.3284497559070587
Epoch: 355,Loss: 0.32844823598861694
Epoch: 356,Loss: 0.32844677567481995
Epoch: 357,Loss: 0.3284452259540558
Epoch: 358,Loss: 0.3284437358379364
Epoch: 359,Loss: 0.32844218611717224
Epoch: 360,Loss: 0.32844078540802
Epoch: 361,Loss: 0.32843923568725586
Epoch: 362,Loss: 0.3284376561641693
Epoch: 363,Loss: 0.3284361660480499
Epoch: 364,Loss: 0.32843437790870667
Epoch: 365,Loss: 0.32843270897865295
Epoch: 366,Loss: 0.32843098044395447
Epoch: 367,Loss: 0.32842928171157837
Epoch: 368,Loss: 0.32842761278152466
Epoch: 369,Loss: 0.3284260034561157
Epoch: 370,Loss: 0.3284243047237396
Epoch: 371,Loss: 0.3284227252006531
Epoch: 372,Loss: 0.32842114567756653
Epoch: 373,Loss: 0.32841956615448
Epoch: 374,Loss: 0.32841813564300537
Epoch: 375,Loss: 0.3284166157245636
Epoch: 376,Loss: 0.3284151554107666
Epoch: 377,Loss: 0.3284136950969696
Epoch: 378,Loss: 0.32841214537620544
Epoch: 379,Loss: 0.32841062545776367
Epoch: 380,Loss: 0.3284090757369995
Epoch: 381,Loss: 0.3284076750278473
Epoch: 382,Loss: 0.3284061849117279
Epoch: 383,Loss: 0.3284046947956085
Epoch: 384,Loss: 0.3284032344818115
Epoch: 385,Loss: 0.32840171456336975
Epoch: 386,Loss: 0.32840025424957275
Epoch: 387,Loss: 0.32839885354042053
Epoch: 388,Loss: 0.3283974230289459
Epoch: 389,Loss: 0.3283960223197937
Epoch: 390,Loss: 0.32839447259902954
Epoch: 391,Loss: 0.32839295268058777
Epoch: 392,Loss: 0.328391432762146
Epoch: 393,Loss: 0.3283899426460266
Epoch: 394,Loss: 0.32838842272758484
Epoch: 395,Loss: 0.3283868432044983
Epoch: 396,Loss: 0.32838529348373413
Epoch: 397,Loss: 0.3283837139606476
Epoch: 398,Loss: 0.32838213443756104
Epoch: 399,Loss: 0.3283804953098297
Epoch: 400,Loss: 0.3283788859844208
Epoch: 401,Loss: 0.32837721705436707
Epoch: 402,Loss: 0.32837551832199097
Epoch: 403,Loss: 0.32837384939193726
Epoch: 404,Loss: 0.32837188243865967
Epoch: 405,Loss: 0.328370064496994
Epoch: 406,Loss: 0.328368216753006
Epoch: 407,Loss: 0.32836639881134033
Epoch: 408,Loss: 0.3283645808696747
Epoch: 409,Loss: 0.3283626139163971
Epoch: 410,Loss: 0.3283606469631195
Epoch: 411,Loss: 0.32835853099823
Epoch: 412,Loss: 0.32835647463798523
Epoch: 413,Loss: 0.32835423946380615
Epoch: 414,Loss: 0.3283519148826599
Epoch: 415,Loss: 0.32834941148757935
Epoch: 416,Loss: 0.3283470571041107
Epoch: 417,Loss: 0.32834485173225403
Epoch: 418,Loss: 0.3283427059650421
Epoch: 419,Loss: 0.32834064960479736
Epoch: 420,Loss: 0.32833853363990784
Epoch: 421,Loss: 0.3283364474773407
Epoch: 422,Loss: 0.32833442091941833
Epoch: 423,Loss: 0.32833224534988403
Epoch: 424,Loss: 0.32832980155944824
Epoch: 425,Loss: 0.328327476978302
Epoch: 426,Loss: 0.32832518219947815
Epoch: 427,Loss: 0.3283226191997528
Epoch: 428,Loss: 0.32832011580467224
Epoch: 429,Loss: 0.3283176124095917
Epoch: 430,Loss: 0.3283149003982544
Epoch: 431,Loss: 0.3283122777938843
Epoch: 432,Loss: 0.3283097743988037
Epoch: 433,Loss: 0.328307181596756
Epoch: 434,Loss: 0.3283044695854187
Epoch: 435,Loss: 0.3283018171787262
Epoch: 436,Loss: 0.3282991647720337
Epoch: 437,Loss: 0.3282964825630188
Epoch: 438,Loss: 0.3282938301563263
Epoch: 439,Loss: 0.3282913267612457
Epoch: 440,Loss: 0.32828882336616516
Epoch: 441,Loss: 0.32828637957572937
Epoch: 442,Loss: 0.32828402519226074
Epoch: 443,Loss: 0.3282817006111145
Epoch: 444,Loss: 0.32827940583229065
Epoch: 445,Loss: 0.3282771110534668
Epoch: 446,Loss: 0.3282747268676758
Epoch: 447,Loss: 0.32827210426330566
Epoch: 448,Loss: 0.32826948165893555
Epoch: 449,Loss: 0.32826700806617737
Epoch: 450,Loss: 0.32826465368270874
Epoch: 451,Loss: 0.3282622694969177
Epoch: 452,Loss: 0.3282598853111267
Epoch: 453,Loss: 0.3282577097415924
Epoch: 454,Loss: 0.3282555639743805
Epoch: 455,Loss: 0.32825329899787903
Epoch: 456,Loss: 0.32825106382369995
Epoch: 457,Loss: 0.3282487690448761
Epoch: 458,Loss: 0.328246533870697
Epoch: 459,Loss: 0.3282442092895508
Epoch: 460,Loss: 0.3282419741153717
Epoch: 461,Loss: 0.32823967933654785
Epoch: 462,Loss: 0.3282374143600464
Epoch: 463,Loss: 0.3282351493835449
Epoch: 464,Loss: 0.32823288440704346
Epoch: 465,Loss: 0.328230619430542
Epoch: 466,Loss: 0.3282284140586853
Epoch: 467,Loss: 0.328226238489151
Epoch: 468,Loss: 0.3282240331172943
Epoch: 469,Loss: 0.32822176814079285
Epoch: 470,Loss: 0.32821953296661377
Epoch: 471,Loss: 0.3282173275947571
Epoch: 472,Loss: 0.3282151222229004
Epoch: 473,Loss: 0.3282128572463989
Epoch: 474,Loss: 0.32821065187454224
Epoch: 475,Loss: 0.3282085657119751
Epoch: 476,Loss: 0.3282065689563751
Epoch: 477,Loss: 0.32820457220077515
Epoch: 478,Loss: 0.3282024562358856
Epoch: 479,Loss: 0.3282003700733185
Epoch: 480,Loss: 0.3281984031200409
Epoch: 481,Loss: 0.32819637656211853
Epoch: 482,Loss: 0.32819443941116333
Epoch: 483,Loss: 0.32819241285324097
Epoch: 484,Loss: 0.3281906247138977
Epoch: 485,Loss: 0.32818883657455444
Epoch: 486,Loss: 0.32818692922592163
Epoch: 487,Loss: 0.3281850516796112
Epoch: 488,Loss: 0.328183114528656
Epoch: 489,Loss: 0.32818111777305603
Epoch: 490,Loss: 0.32817918062210083
Epoch: 491,Loss: 0.32817724347114563
Epoch: 492,Loss: 0.3281753361225128
Epoch: 493,Loss: 0.32817336916923523
Epoch: 494,Loss: 0.3281714618206024
Epoch: 495,Loss: 0.3281695246696472
Epoch: 496,Loss: 0.3281676173210144
Epoch: 497,Loss: 0.328165739774704
Epoch: 498,Loss: 0.32816383242607117
Epoch: 499,Loss: 0.3281618356704712
Epoch: 500,Loss: 0.328159898519516
Epoch: 501,Loss: 0.3281579315662384
Epoch: 502,Loss: 0.3281560242176056
Epoch: 503,Loss: 0.328154057264328
Epoch: 504,Loss: 0.3281521499156952
Epoch: 505,Loss: 0.32815030217170715
Epoch: 506,Loss: 0.32814842462539673
Epoch: 507,Loss: 0.3281465470790863
Epoch: 508,Loss: 0.32814472913742065
Epoch: 509,Loss: 0.32814285159111023
Epoch: 510,Loss: 0.32814106345176697
Epoch: 511,Loss: 0.3281392455101013
Epoch: 512,Loss: 0.32813751697540283
Epoch: 513,Loss: 0.3281356692314148
Epoch: 514,Loss: 0.3281339108943939
Epoch: 515,Loss: 0.32813215255737305
Epoch: 516,Loss: 0.3281303346157074
Epoch: 517,Loss: 0.3281285762786865
Epoch: 518,Loss: 0.3281267583370209
Epoch: 519,Loss: 0.32812488079071045
Epoch: 520,Loss: 0.32812297344207764
Epoch: 521,Loss: 0.3281210958957672
Epoch: 522,Loss: 0.3281193673610687
Epoch: 523,Loss: 0.3281174898147583
Epoch: 524,Loss: 0.3281155526638031
Epoch: 525,Loss: 0.3281136155128479
Epoch: 526,Loss: 0.3281117081642151
Epoch: 527,Loss: 0.32810983061790466
Epoch: 528,Loss: 0.32810795307159424
Epoch: 529,Loss: 0.328106164932251
Epoch: 530,Loss: 0.32810452580451965
Epoch: 531,Loss: 0.32810288667678833
Epoch: 532,Loss: 0.3281012177467346
Epoch: 533,Loss: 0.3280995786190033
Epoch: 534,Loss: 0.32809799909591675
Epoch: 535,Loss: 0.32809633016586304
Epoch: 536,Loss: 0.32809484004974365
Epoch: 537,Loss: 0.3280932903289795
Epoch: 538,Loss: 0.32809174060821533
Epoch: 539,Loss: 0.32809022068977356
Epoch: 540,Loss: 0.3280887007713318
Epoch: 541,Loss: 0.3280872106552124
Epoch: 542,Loss: 0.32808569073677063
Epoch: 543,Loss: 0.3280841112136841
Epoch: 544,Loss: 0.3280825614929199
Epoch: 545,Loss: 0.3280809819698334
Epoch: 546,Loss: 0.328079491853714
Epoch: 547,Loss: 0.32807794213294983
Epoch: 548,Loss: 0.32807645201683044
Epoch: 549,Loss: 0.32807493209838867
Epoch: 550,Loss: 0.3280734121799469
Epoch: 551,Loss: 0.3280719518661499
Epoch: 552,Loss: 0.3280705511569977
Epoch: 553,Loss: 0.3280690908432007

In [116]:
print(f"Predictions count: {predictions.shape[0]}")
print(f"Labels count: {Y_test_tensor.shape[0]}")
print(Y_train_tensor.shape)

Predictions count: 2000
Labels count: 2000
torch.Size([8000, 1])

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

Reusing TensorBoard on port 6006 (pid 15985), started 0:00:09 ago. (Use '!kill 15985' to kill it.)

In [105]:
model.eval()
with torch.no_grad():
    test_outputs = model(X_test_tensor.to(torch.float32)) 
    
    predictions = (test_outputs >= 0.5).float()
    
    Y_test_actual = Y_test_tensor.view(-1, 1).to(torch.float32)
    
    correct = (predictions == Y_test_actual).sum().item()
    accuracy = (correct / Y_test_actual.size(0)) * 100

print(f"Accuracy: {accuracy:.2f}%")

Accuracy: 86.15%

In [107]:
predictions.shape

torch.Size([2000, 1])

In [108]:
from sklearn.metrics import confusion_matrix

In [109]:
confusion_matrix = (Y_test_tensor,predictions)

In [110]:
confusion_matrix

(tensor([0, 0, 0,  ..., 1, 1, 1]),
 tensor([[0.],
         [0.],
         [0.],
         ...,
         [1.],
         [0.],
         [0.]]))

In [111]:
torch.save(model.state_dict(),'ann_model_weights.pth')

In [112]:
torch.save(model,'Ann-model.pth')